// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASwlktOkXDTZOtTe3YuU3GHVg7spYH7h8',
    appId: '1:587480634133:web:faa10a51703e2626a50f1c',
    messagingSenderId: '587480634133',
    projectId: 'login-signup-94458',
    authDomain: 'login-signup-94458.firebaseapp.com',
    databaseURL: 'https://login-signup-94458-default-rtdb.firebaseio.com',
    storageBucket: 'login-signup-94458.appspot.com',
    measurementId: 'G-28PHRW66WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANyn0uFUXieicIfQaT4lkErbfeMSTa1Zo',
    appId: '1:587480634133:android:3317c4cae0f1e218a50f1c',
    messagingSenderId: '587480634133',
    projectId: 'login-signup-94458',
    databaseURL: 'https://login-signup-94458-default-rtdb.firebaseio.com',
    storageBucket: 'login-signup-94458.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBHMlPku4pfa2OnvyP6Y1NFUcE1_ORQjc',
    appId: '1:587480634133:ios:7426e9c39447b5dba50f1c',
    messagingSenderId: '587480634133',
    projectId: 'login-signup-94458',
    databaseURL: 'https://login-signup-94458-default-rtdb.firebaseio.com',
    storageBucket: 'login-signup-94458.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBHMlPku4pfa2OnvyP6Y1NFUcE1_ORQjc',
    appId: '1:587480634133:ios:0abca9d26bb9ff5ba50f1c',
    messagingSenderId: '587480634133',
    projectId: 'login-signup-94458',
    databaseURL: 'https://login-signup-94458-default-rtdb.firebaseio.com',
    storageBucket: 'login-signup-94458.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
